[versions]
agp = "8.4.0"
kotlin = "1.9.23"
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycle = "2.8.2"
smack = "4.4.6"
coroutines = "1.8.1"
recyclerview = "1.3.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.9.0" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
smack-android = { group = "org.igniterealtime.smack", name = "smack-android", version.ref = "smack" }
smack-tcp = { group = "org.igniterealtime.smack", name = "smack-tcp", version.ref = "smack" }
smack-im = { group = "org.igniterealtime.smack", name = "smack-im", version.ref = "smack" }
smack-extensions = { group = "org.igniterealtime.smack", name = "smack-extensions", version.ref = "smack" }
smack-sasl-provided = { group = "org.igniterealtime.smack", name = "smack-sasl-provided", version.ref = "smack" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
